[package]
name = "beater"
version = "0.1.0"
authors = ["Vinícius Manuel Martins"]
edition = "2021"
description = "Beater is a 3D modelling software"
license = "MIT"

[dependencies]
anyhow = "1.0.93"
ash = "0.38.0"
bytemuck = "1.20.0"
gpu-allocator = "0.27.0"
image = "0.25.5"
